### ISSUE TITLE
Can you make it accept non maven artifacts?

### ISSUE THREAD

**Issue by naiduv** [ThoughtWorksInc/go-artifactory-poller#4]
Please, pretty please.
I am trying to do this myself, but it would be alot quick for you :D

**Comment by EasyAsABC123** [comment]
this needs to be added.

**Comment by mdaliejaz** [comment]
Would any of you be interested in sending a PR for this?

**Comment by EasyAsABC123** [comment]
@mdaliejaz just using https://github.com/varchev/go-generic-artifactory-poller

**Comment by mdaliejaz** [comment]
Wow... that's great. I didn't know about this plugin.
I'll talk to Varchev if his plugin could be listed on [plugins page](http://www.go.cd/community/plugins.html).
